version: "3.9"
services:
    redis:
        image: "redis:latest"
        restart: "unless-stopped"
        ports:
            - "6379:6379"
    dashboard:
        build: .
        restart: "unless-stopped"
        ports: 
            - "8000:8000"
        environment:
            - REDIS_URL=redis://redis:6379
        depends_on:
            - "redis"
